filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
filebeat.inputs:
  - type: filestream
    id: buzzer-logs
    paths:
      - /app/log/*.log

output.logstash:
  hosts: ["34.244.138.163:5044"]
  index: buzzer
