---
- name: a git checkout that runs on local host
  local_action: git repo=ssh://git@github.com:ZanichelliEditore/buzzer.git dest=src version=origin/{{ checkout_branch }} accept_hostkey=yes
  become: false
  notify: remove local checkout
